// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopBridge.Persistence;

namespace ShopBridge.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShopBridge.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Mobiles"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Laptops"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "TV"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Cameras"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Music Instruments"
                        });
                });

            modelBuilder.Entity("ShopBridge.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "OnePlus Nord CE 5G (Charcoal Ink, 8GB RAM, 128GB Storage)",
                            PhotoPath = "images/oneplus.png",
                            Price = 24999.00m,
                            ProductName = "OnePlus",
                            Quantity = 3
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "OnePlus 9R 5G (Lake Blue, 8GB RAM, 128GB Storage)",
                            PhotoPath = "images/oneplus9R.png",
                            Price = 39999.00m,
                            ProductName = "OnePlus",
                            Quantity = 5
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 2,
                            Description = "Acer Nitro 5 Intel Core i5-11th Generation 144 Hz Refresh Rate 15.6-inch (39.62 cms) Gaming Laptop (8GB Ram/512 GB SSD/Win10/GTX 1650 Graphics/Obsidian Black/2.2 Kgs), AN515-56 + Xbox Game Pass for PC",
                            PhotoPath = "images/Acer.png",
                            Price = 72994.00m,
                            ProductName = "Acer Nitro",
                            Quantity = 3
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Description = "2020 Apple MacBook Pro (13.3-inch/33.78 cm, 8GB RAM, 256GB SSD, 1.4GHz Quad-core 8th-Generation Intel Core i5 Processor, Two Thunderbolt 3 Ports) - Space Grey",
                            PhotoPath = "images/Apple.png",
                            Price = 99990.00m,
                            ProductName = "Apple MacBook Pro",
                            Quantity = 10
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 5,
                            Description = "Casio CT-S200 Casiotone 61-Key Portable Keyboard (Red)",
                            PhotoPath = "images/Casio.png",
                            Price = 7595.00m,
                            ProductName = "Casio",
                            Quantity = 7
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 5,
                            Description = "Ashton D10C 39-inch Cutaway Acoustic Guitar",
                            PhotoPath = "images/Guitar.png",
                            Price = 7595.00m,
                            ProductName = "Guitar",
                            Quantity = 2
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3,
                            Description = "Samsung 138 cm (55 inches) Crystal 4K Pro Series Ultra HD Smart LED TV UA55AUE70AKLXL (Black) (2021 Model)",
                            PhotoPath = "images/TV.png",
                            Price = 54999.00m,
                            ProductName = "Samsung Smart TV",
                            Quantity = 2
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 4,
                            Description = "Sony Alpha ILCE-6400M 24.2MP Mirrorless Digital SLR Camera (Black) with 18-135mm Power Zoom Lens (APS-C Sensor, Real-Time Eye Auto Focus, 4K Vlogging Camera, Tiltable LCD) - Black",
                            PhotoPath = "images/SonyCamera.png",
                            Price = 102499.00m,
                            ProductName = "Sony Microless Camera",
                            Quantity = 5
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 4,
                            Description = "Canon EOS 200D II 24.1MP Digital SLR Camera + EF-S 18-55mm is STM Lens + EF-S 55-250mm is STM Lens (Black)",
                            PhotoPath = "images/Canon.png",
                            Price = 62220.00m,
                            ProductName = "Canon Camera",
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("ShopBridge.Models.Product", b =>
                {
                    b.HasOne("ShopBridge.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
